version: "3.5"
services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "nginx"
    networks:
      - elk

  microservice:
    container_name: microservice-rc
    image: node:16
    working_dir: /usr/src/microservice-rc
    command: bash -c "npm install --only=prod && npm start"
    volumes:
      - ./app/:/usr/src/microservice-rc
      - ./app/package.json:/usr/src/microservice-rc/package.json
    ports:
      - "3000:3000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: rc-microservice
    networks:
      - elk
networks:

  elk:
    driver: bridge
