version: "3.5"
services:
  # fluentd:
  #   container_name: fluentd
  #   build: ./fluentd
  #   ports:
  #     - "24224:24224"
  #     - "24224:24224/udp"
  #   volumes:
  #     - "./fluentd/pipeline/fluent.conf:/fluentd/etc/fluent.conf"
  #   networks:
  #     - elk

  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit:1.2
    entrypoint:
      [
        "/fluent-bit/bin/fluent-bit",
        "-c",
        "/fluent-bit/etc/fluent-bit.conf"
      ]
    # environment:
    #   - FLUENTD_AGGREGATOR_HOST=192.168.1.106
    #   - FLUENTD_AGGREGATOR_PORT=24224
    ports:
      - "24224:24224"
    volumes:
      - "./fluent-bit/:/fluent-bit/etc/"
      - "./nginx/log/:/var/log/nginx"
    networks:
      - elk

  web:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log/:/var/log/nginx
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
    networks:
      - elk

  microservice:
    container_name: microservice-rc
    image: node:16
    working_dir: /usr/src/microservice-rc
    command: bash -c "npm install --only=prod && npm start"
    volumes:
      - ./app/:/usr/src/microservice-rc
      - ./app/package.json:/usr/src/microservice-rc/package.json
    ports:
      - "3000:3000"
    depends_on:
      - fluent-bit
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: rc-microservice
    networks:
      - elk
networks:

  elk:
    driver: bridge
