version: '3.7'
services:

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.16.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  fluentd:
    container_name: fluentd
    build: ./fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - "./fluentd/pipeline:/fluentd/etc"
    networks:
      - elk

volumes:
  esdata:
    driver: local
